services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ENVIRONMENT=docker
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - FILE_PATH=/app/${FILE_PATH}
      - CHUNK_SIZE=${CHUNK_SIZE}
    volumes:
      - ./${FILE_PATH}:/app/${FILE_PATH}
    deploy:
      resources:
        limits:
          cpus: '4'

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: